languageCode:           "en"
title:                  "Schedule Url"
baseURL:                "https://scheduleurl.com"
enableInlineShortcodes: true

markup:
  goldmark:
    renderer:
      unsafe:           true
  highlight:
    noClasses:          false
  tableOfContents:
    startLevel:         2
    endLevel:           6

buildDrafts:            true
buildFuture:            true

enableRobotsTXT:        true
metaDataFormat:         "yaml"
disableKinds:           ["404", "taxonomy", "taxonomyTerm", "RSS"]

publishDir:             "docs"

module:
  mounts:
    - source:           node_modules/bootstrap/dist
      target:           static/bootstrap/dist
    - source:           static
      target:           static

params:
  name: "Schedule Url"
  description:          "Schedule Url is like a utility extension which helps user to schedule a webpage / url to open at particular day and time."
  authors:              "Dhruv Patel, Dharmesh Patel, and Schedule URL contributors"
  current_version:      "1.0.0"
  previous_version:     "1.0.0"
  docs_version:         "1.x"
  github_org:           "https://github.com/Dhruv-Techapps"
  repo:                 "https://github.com/Dhruv-Techapps/scheduleurl"
  twitter:              "dhruvtechapps"
  discord:              "https://discord.gg/vmnNfWKqnR"
  youtube:              "https://www.youtube.com/channel/UCj1acOGkIYR59furcg28nzA"
  blog:                 "https://blog.scheduleurl.com/"
  examples:             "https://examples.scheduleurl.com/"

  download:
    chrome:
      dev: "https://chrome.google.com/webstore/detail/cdjfjpoffkbfepobmlegdknkbddecodc"
    Edge:
      dev: "https://microsoftedge.microsoft.com/addons/detail/ipcbjmjendjpocfggdpcjnbadeefdppn"

  cdn:
    css: "https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css"
    css_hash: "sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl"
    js: "https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.min.js"
    js_hash: "sha384-nsg8ua9HAw1y0W1btsyWgBklPnCUAFLuTMS2G72MMONqmOymq585AcH49TLBQObG"
    js_bundle: "https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js"
    js_bundle_hash: "sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0"
    popper: "https://cdn.jsdelivr.net/npm/@popperjs/core@2.6.0/dist/umd/popper.min.js"
    popper_hash: "sha384-KsvD1yqQ1/1+IA7gi3P0tyJcT3vR+NdBTt13hSJ2lnve8agRGXTTyNaBYmCR/Nwi"
