languageCode:           "en"
title:                  "Schedule Url"
baseURL:                "https://scheduleurl.com"
enableInlineShortcodes: true

markup:
  goldmark:
    renderer:
      unsafe:           true
  highlight:
    noClasses:          false
  tableOfContents:
    startLevel:         2
    endLevel:           6

buildDrafts:            true
buildFuture:            true

enableRobotsTXT:        true
metaDataFormat:         "yaml"
disableKinds:           ["404", "taxonomy", "taxonomyTerm", "RSS"]

publishDir:             "docs"

module:
  mounts:
    - source:           node_modules/bootstrap/dist
      target:           static/bootstrap/dist
    - source:           static
      target:           static

params:
  name: "Schedule Url"
  description:          "Schedule Url is like a utility extension which helps user to schedule a webpage / url to open at particular day and time."
  authors:              "Dhruv Patel, Dharmesh Patel, and Schedule URL contributors"
  current_version:      "1.0.0-dev"
  previous_version:     "1.0.0"
  docs_version:         "1.0"
  github_org:           "https://github.com/Dhruv-Techapps"
  repo:                 "https://github.com/Dhruv-Techapps/scheduleurl"
  twitter:              "dhruvtechapps"
  discord:              "https://discord.gg/vmnNfWKqnR"
  youtube:              "https://www.youtube.com/channel/UCj1acOGkIYR59furcg28nzA"
  blog:                 "https://blog.scheduleurl.com/"
  examples:             "https://examples.scheduleurl.com/"

  download:
    chrome:
      dev: "https://chrome.google.com/webstore/detail/cpjikgcdmhfnmaiibplplldlchbjejel"
      dev_version: 1.0.0
    Edge:
      dev: "https://microsoftedge.microsoft.com/addons/detail/auto-clicker-autofill-/pmckiknbinanfnmbichcncmfpbcfpocn"
      dev_version: 1.0.0

  cdn:
    css:              "https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-alpha3/dist/css/bootstrap.min.css"
    css_hash:         "sha384-CuOF+2SnTUfTwSZjCXf01h7uYhfOBuxIhGKPbfEJ3+FqH/s6cIFN9bGr1HmAg4fQ"
    js:               "https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-alpha3/dist/js/bootstrap.min.js"
    js_hash:          "sha384-t6I8D5dJmMXjCsRLhSzCltuhNZg6P10kE0m0nAncLUjH6GeYLhRU1zfLoW3QNQDF"
    js_bundle:        "https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-alpha3/dist/js/bootstrap.bundle.min.js"
    js_bundle_hash:   "sha384-popRpmFF9JQgExhfw5tZT4I9/CI5e2QcuUZPOVXb1m7qUmeR2b50u+YFEYe1wgzy"
    popper:           "https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
    popper_hash:      "sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
